Repository mapbox/vision-ios-examples, pull requests merged in 2019-05, with the labels that each got.

#72 Minor update in README file
  README.md
Labels: P1, documentation, enhancement, iOS

#70 Create new IDETemplate macros and update file headers
  demo.xcodeproj/project.xcworkspace/xcshareddata/IDETemplateMacros.plist
  demo/ARContainerViewController.swift
  demo/ARMapNavigationController.swift
  demo/AlertPlayer.swift
  demo/AppDelegate.swift
  demo/CollisionObjectView.swift
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
  demo/DelegateProxy.swift
  demo/DistanceView.swift
  demo/ImageSwitchingView.swift
  demo/License/LicenseChecker.swift
  demo/License/WelcomeViewController.swift
  demo/MapViewController.swift
  demo/MenuViewController.swift
  demo/PaddedLabel.swift
  demo/RoadLanesView.swift
  demo/SafetyState.swift
  demo/Signs.swift
  demo/Tracker.swift
  demo/UIButton+BackgroudColor.swift
  demoTests/Mocks/MockAlertPlayer.swift
  demoTests/Mocks/MockContainerPresenter.swift
  demoTests/SafetyScreenTestCase.swift
Labels: P2, enhancement, iOS

#77 Add fake support for UK signs to make ready-for-build `demo` app
  demo/Signs.swift
Labels: P0, bug, iOS, invalid, wontfix

#79 Release/0.4.0 to dev
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  demo/ContainerInteractor.swift
  demo/DelegateProxy.swift
Labels: iOS

#78 Release/0.4.0 to master
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  README.md
  Resources/Assets.xcassets/lane-departure-notification.imageset/Contents.json
  Resources/Assets.xcassets/lane-departure-notification.imageset/lane-departure-notification.pdf
  Resources/lane_departure_warning.wav
  demo.xcodeproj/project.pbxproj
  demo/AlertPlayer.swift
  demo/AppDelegate.swift
  demo/CollisionObjectView.swift
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
  demo/DelegateProxy.swift
  demo/DistanceFormatter.swift
  demo/License/WelcomeViewController.swift
  demo/PaddedLabel.swift
  demo/Signs.swift
  demoTests/Mocks/MockContainerPresenter.swift
Labels: iOS
