Repository mapbox/vision-ios-examples, pull requests merged in 2019-04, with the labels that each got.

#45 Support Country from Delegate
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
  demo/VisionDelegateProxy.swift
Labels: vision

#46 Adopt to new API
  demo.xcodeproj/xcshareddata/xcschemes/demo.xcscheme
  demo/ARContainerViewController.swift
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
Labels: vision, vision ar, vision core

#48 Support Other countries
  demo/Signs.swift
Labels: vision core

#53 Update Carthage dependencies
  Cartfile.resolved
Labels: enhancement
