Repository mapbox/vision-ios-examples, pull requests merged in 2019-07, with the labels that each got.

#90 MapboxNavigation and MapboxDirections dependencies
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  demo.xcodeproj/project.pbxproj
  demo/ARRoute+DirectionsRoute.swift
Labels: P1, iOS

#86 Apply linter checks and fix issues
  .swift-version
  .swiftformat
  .swiftlint.yml
  demo.xcodeproj/project.pbxproj
  demo/ARContainerViewController.swift
  demo/ARMapNavigationController.swift
  demo/AlertPlayer.swift
  demo/AppDelegate.swift
  demo/CollisionObjectView.swift
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
  demo/DelegateProxy.swift
  demo/DistanceFormatter.swift
  demo/DistanceView.swift
  demo/ImageSwitchingView.swift
  demo/License/LicenseChecker.swift
  demo/License/LicenseViewController.swift
  demo/Locale.swift
  demo/MapViewController.swift
  demo/MenuViewController.swift
  demo/OrderedDictionary.swift
  demo/PaddedLabel.swift
  demo/RoadLanesView.swift
  demo/SafetyState.swift
  demo/Signs.swift
  demo/Tracker.swift
  demo/UIButton+BackgroudColor.swift
  demoTests/Mocks/MockAlertPlayer.swift
  demoTests/Mocks/MockContainerPresenter.swift
  demoTests/SafetyScreenTestCase.swift
Labels: P1, enhancement, iOS

#96 Update linter versions/configs
  .swiftformat
  .swiftlint.yml
  demo/OrderedDictionary.swift
  demo/Signs.swift
Labels: P1, enhancement, iOS, operation excellence

#99 Release/0.5.0 to dev
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
Labels: iOS

#93 Integrate secret-shield tool for `vision-ios-examples`
  README.md
Labels: P0, documentation, enhancement, iOS, operation excellence
