Repository mapbox/vision-ios-examples, pull requests merged in 2020-02, with the labels that each got.

#128 Update changelog
  CHANGELOG.md
Labels: Release, iOS

#129 Support match for Teaser
  Matchfile
Labels: iOS

#130 Remove Object Mapping screen
  CHANGELOG.md
  Resources/Assets.xcassets/icon5.imageset/Contents.json
  Resources/Assets.xcassets/icon5.imageset/icon5.pdf
  Resources/en.lproj/Localizable.strings
  demo.xcodeproj/project.pbxproj
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
  demo/MapViewController.swift
  demo/MenuViewController.swift
Labels: iOS

#126 Release/0.11.0 to dev
  CHANGELOG.md
  Cartfile
  Matchfile
  Resources/Assets.xcassets/icon5.imageset/Contents.json
  Resources/Assets.xcassets/icon5.imageset/icon5.pdf
  Resources/en.lproj/Localizable.strings
  demo.xcodeproj/project.pbxproj
  demo/ARRoute+DirectionsRoute.swift
  demo/ContainerInteractor.swift
  demo/ContainerViewController.swift
  demo/MapViewController.swift
  demo/MenuViewController.swift
Labels: P0, Release, iOS

#132 Adapt to model performance API change
  demo/ContainerInteractor.swift
Labels: iOS
